### ISSUE TITLE
FR: Sales-based searching

### ISSUE THREAD

**Issue by AaronCRobinson** [hashkitty/ckwallet-web#1]
There does not appear to be a keyword to search for only kitties on sale. Also there is currently no information displayed about the cost of a kitty. Let me know if I can provide anymore info about this feature request.

**Comment by AaronCRobinson** [comment]
This request came from an interaction with `luigi#4748` who was looking for this feature.

**Comment by hashkitty** [comment]
Now you can use "sale" or "sire" keyword to filter by sale/siring auction in progress
